server:
  port: 4040

logging:
  level: 
    root: INFO
  file:
    path: ./logs

spring:
  datasource:
    url: 
    username: 
    password: 
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: 
        format_sql: true
        id:
          new_generator_mappings: false
    open-in-view: false